import Head from 'next/head'
import Ads from '../components/AdsSection/Ads'
import FreshDrop from '../components/FreshDrop/FreshDrop'
import Hero from '../components/Hero/Hero'
import HotProducts from '../components/HotProducts/HotProducts'
import Menu from '../components/Menu/Menu'
import Image from 'next/image'
import PromotionSection from '../components/PromotionSection/PromotionSection'
export default function Home() {
    return (
        <div className="text-primary">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <Hero />
            <main className="max-w-[1536px] px-4 mx-auto">
                <Ads />
                <HotProducts />
                <FreshDrop />
                <div>
                    <Image
                        src="/images/Newsletter.png"
                        alt=""
                        width={1536}
                        height={572}
                    />
                </div>
                <PromotionSection />
            </main>
        </div>
    )
}
