import Head from 'next/head'
import Hero from '../components/Hero/Hero'
import Menu from '../components/Menu/Menu'

export default function Home() {
    return (
        <div className="text-primary">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <Hero />
            <main className="max-w-[1536px] mx-auto"></main>
        </div>
    )
}
