import Head from 'next/head'
import { useState } from 'react'
import Footer from '../components/Footer/Footer'
import Menu from '../components/Menu/Menu'
import firebase from 'firebase/app'
import 'firebase/auth'
const Login = () => {
    const [email, setEmail] = useState<string>('')
    const [password, setPassword] = useState<string>('')
    const login = async (email, password) => {
        await firebase
            .auth()
            .signInWithEmailAndPassword(email, password)
            .then(() => {
                window.location.href = '/'
            })
            .catch((err) => {
                console.log(err)
            })
    }

    const signUp = async (email, password) => {
        await firebase
            .auth()
            .createUserWithEmailAndPassword(email, password)
            .then(() => {
                window.location.href = '/'
            })
            .catch((err) => {
                console.log(err)
            })
    }

    return (
        <div className="text-primary">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <div className="flex flex-col justify-center items-center py-12 ">
                <div>
                    <h2>Logowanie</h2>
                    <div className="flex flex-col space-y-3">
                        <input
                            name="username"
                            placeholder="Email"
                            type="text"
                            className="bg-gray-200 rounded-xl px-2 py-1 outline-none"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                        />
                        <input
                            name="password"
                            placeholder="Password"
                            type="password"
                            className="bg-gray-200 rounded-xl px-2 py-1 outline-none"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                        />
                        <div className="flex justify-between">
                            <button
                                type="submit"
                                className="bg-green-500 rounded-2xl py-2 px-4 text-[#fff]"
                                onClick={() => login(email, password)}
                            >
                                Zaloguj
                            </button>
                            <div
                                className="bg-red-500 rounded-2xl py-2 px-4 text-[#fff] cursor-pointer"
                                onClick={() => signUp(email, password)}
                            >
                                Rejestracja
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    )
}

export default Login
